---
name: Support request
about: Ask for help or seek clarification about the project
title: "[SPT]"
labels: help wanted
assignees: drachenpapa

---

**Description**
Briefly describe what you need help with or what you don't understand.

**Steps to reproduce**
If applicable, list the steps you took that led to your confusion or problem.

**Expected behavior**
If applicable, describe what you expected to happen.

**Actual behavior**
If applicable, describe what actually happened instead.

**Additional information**
Add any other context or screenshots about the support request here.
