name: Generate SBOM

on:
  release:
    types: [ created ]
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  generate-sbom:
    name: Generate SBOM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Syft
        run: curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
      - name: Generate SBOMs
        run: syft . -o spdx-json > sbom.spdx.json
      - name: Install Cosign
        uses: sigstore/cosign-installer@v3
      - name: Sign SBOMs
        run: cosign sign-blob --yes --output-signature sbom.spdx.json.sig --output-certificate sbom.spdx.json.cert sbom.spdx.json
        shell: bash
      - name: Verify signed SBOMs
        run: |
          cosign verify-blob --certificate sbom.spdx.json.cert \
          --certificate-identity "https://github.com/drachenpapa/zatacka/.github/workflows/generate-sbom.yml@refs/heads/main" \
          --certificate-oidc-issuer "https://token.actions.githubusercontent.com" \
          --signature sbom.spdx.json.sig \
          sbom.spdx.json
      - name: Upload as artifact
        uses: actions/upload-artifact@v4
        with:
          name: sboms
          path: |
            sbom.spdx.json
            sbom.spdx.json.sig
            sbom.spdx.json.cert
      - name: Upload to release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          files: |
            sbom.spdx.json
            sbom.spdx.json.sig
            sbom.spdx.json.cert
