name: Snyk Security

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  snyk_scans:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: SAST (Static Application Security Testing)
            scan-name: Scan with SnykCode
            snyk-cmd: 'snyk code test --severity-threshold=medium --sarif-file-output=snyk-sast.sarif || true'
            sarif-file: snyk-sast.sarif
            category: sast
          - name: SCA (Software Composition Analysis)
            scan-name: Scan with Snyk Open Source
            snyk-cmd: 'snyk test --severity-threshold=medium --sarif-file-output=snyk-sca.sarif || true'
            sarif-file: snyk-sca.sarif
            category: sca
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Snyk CLI
        run: npm install -g snyk
      - name: ${{ matrix.scan-name }}
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: ${{ matrix.snyk-cmd }}
      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ matrix.sarif-file }}
          category: ${{ matrix.category }}
