name: PR Validation

on:
  pull_request:
    branches-ignore:
      - 'renovate/*'
    types: [opened, edited, reopened, synchronize]

permissions:
  pull-requests: read

jobs:
  lint-pr-title:
    name: Lint pull request title
    runs-on: ubuntu-latest
    steps:
      - name: Lint title
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            build
            chore
            ci
            docs
            feat
            fix
            refactor
            revert
            test
          requireScope: false
